sudo: required
services:
  - docker

before_install:
  - docker build -t badityaprashant/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true badityaprashant/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-905418485410"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: "$AWS_SECRET_KEY"
